language: go
go:
  - "1.x"
os:
  - linux
  - osx
dist: xenial
sudo: required
env:
  - GOTRACEBACK=all
before_install:
  - ./.cisetup.sh
  - go get golang.org/x/lint/golint
  - go get honnef.co/go/tools/cmd/staticcheck
  - go get -d ./...
  - go get github.com/mikioh/ipaddr
script:
  - go build -tags=gofuzz ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go vet ./...
  - staticcheck ./...
  - golint -set_exit_status ./...
  - go test -race ./...
  - go test -c -tags integration .
  - sudo ./wireguardctrl.test -test.v -test.run TestClientIntegration
